### ISSUE TITLE
Why not "forecast" attribute only

### ISSUE THREAD

**Issue by andreid1303** [Eugeniusz-Gienek/kodi_weather_ha#3]
I think it will be more user friendly creating just "forecast" attribute in HA and parse it in Kodi. 
Also using current data and units from weather entity as attributes.

```
    sensor:
      - name: "DailyWeather"
        unique_id: weather_daily_all_in_one
        state: "{{ states('weather.openweathermap_daily') }}"
        attributes:
          temperature: "{{ state_attr('weather.openweathermap_daily', 'temperature') }}"
          dew_point: "{{ state_attr('weather.openweathermap_daily', 'dew_point') }}"
          temperature_unit: "{{ state_attr('weather.openweathermap_daily', 'temperature_unit') }}"
          humidity: "{{ state_attr('weather.openweathermap_daily', 'humidity') }}"
          cloud_coverage: "{{ state_attr('weather.openweathermap_daily', 'cloud_coverage') }}"
          pressure: "{{ state_attr('weather.openweathermap_daily', 'pressure') }}"
          pressure_unit: "{{ state_attr('weather.openweathermap_daily', 'pressure_unit') }}"
          wind_bearing: "{{ state_attr('weather.openweathermap_daily', 'wind_bearing') }}"
          wind_speed: "{{ state_attr('weather.openweathermap_daily', 'wind_speed') }}"
          wind_speed_unit: "{{ state_attr('weather.openweathermap_daily', 'wind_speed_unit') }}"
          visibility_unit: "{{ state_attr('weather.openweathermap_daily', 'visibility_unit') }}"
          precipitation_unit: "{{ state_attr('weather.openweathermap_daily', 'precipitation_unit') }}"
          forecast: "{{ daily['weather.openweathermap_daily'].forecast }}"
```
